## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

# Import pandas and read the charity_data.csv from the provided cloud URL.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns = ['EIN', 'NAME'])

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff_value = 500
app_count = application_df['APPLICATION_TYPE'].value_counts()
application_types_to_replace = app_count[app_count < cutoff_value].index.tolist()

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classification_list = application_df['CLASSIFICATION'].value_counts()
classification_list

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C1248        1
C6100        1
C1820        1
C1900        1
C2150        1
Name: count, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_list[classification_list>1]

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C6000       15
C1800       15
C1250       14
C8200       11
C1238       10
C1278       10
C1237        9
C1235        9
C7210        7
C1720        6
C2400        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1256        2
C1246        2
C1234        2
C1267        2
Name: count, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
cutoff_value = 1000
class_count = application_df['CLASSIFICATION'].value_counts()
classifications_to_replace = class_count[class_count < cutoff_value].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df, dtype=int)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [13]:
# Split our preprocessed data into our features and target arrays
X = application_df.drop('IS_SUCCESSFUL', axis =1).values
y = application_df['IS_SUCCESSFUL'].values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [14]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [15]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=128, activation='relu', input_dim=X_train.shape[1]))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=64, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 128)            │         5,632 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 13,953 (54.50 KB)

 Trainable params: 13,953 (54.50 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [17]:
# Train the model
history = nn.fit(X_train, y_train, epochs=100, batch_size=64, validation_data=(X_test, y_test))

Epoch 1/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.4932 - loss: 35459.9453 - val_accuracy: 0.5332 - val_loss: 383982.9688
Epoch 2/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5171 - loss: 99738.3203 - val_accuracy: 0.5332 - val_loss: 1407.7197
Epoch 3/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5064 - loss: 49249.6055 - val_accuracy: 0.5332 - val_loss: 15249.6611
Epoch 4/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.5009 - loss: 4269.2256 - val_accuracy: 0.4668 - val_loss: 1736.9286
Epoch 5/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5143 - loss: 25056.6797 - val_accuracy: 0.5332 - val_loss: 15203.9004
Epoch 6/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5081 - loss: 28727.0996 - val_accuracy: 0.5343 - val_loss: 161.6872
Epoch 7/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5079 - loss: 15500.0527 - val_accuracy: 0.4668 - val_loss: 2590.3306
Epoch 8/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4953 - loss: 5484.1104 - val_accuracy: 0.4668 - val_loss: 1170.6937
Epoch 9/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4770 - loss: 6562.6357 - val_accuracy: 0.5332 - val_loss: 9554.9814
Epoch 10/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5003 - loss: 4806.6187 - val_accuracy: 0.5160 - val_loss: 93.7651
Epoch 11/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5216 - loss: 4125.1577 - val_accuracy: 0.5332 - val_loss: 6.3337
Epoch 12/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5208 - loss: 10076.7549 - val_accuracy: 0.5104 - val_loss: 98.1137
Epoch 13/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.5009 - loss: 3531.4617 - val_accuracy: 0.4668 - val_loss: 338.1471
Epoch 14/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5101 - loss: 2437.1411 - val_accuracy: 0.4668 - val_loss: 150.9248
Epoch 15/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.4914 - loss: 288.7550 - val_accuracy: 0.5291 - val_loss: 3.7495
Epoch 16/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.4981 - loss: 421.3624 - val_accuracy: 0.5093 - val_loss: 60.3086
Epoch 17/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5194 - loss: 34.9696 - val_accuracy: 0.5332 - val_loss: 328.2161
Epoch 18/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5308 - loss: 101.2391 - val_accuracy: 0.5332 - val_loss: 0.6912
Epoch 19/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5321 - loss: 0.6913 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 20/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5327 - loss: 0.6910 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 21/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5346 - loss: 0.6908 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 22/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5280 - loss: 0.6916 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 23/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.5275 - loss: 0.6917 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 24/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5308 - loss: 0.6913 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 25/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5331 - loss: 0.6910 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 26/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5307 - loss: 0.6913 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 27/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5347 - loss: 0.6908 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 28/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5304 - loss: 0.6914 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 29/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5367 - loss: 0.6905 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 30/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5233 - loss: 0.6921 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 31/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5269 - loss: 0.6919 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 32/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5313 - loss: 0.6912 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 33/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5324 - loss: 0.6911 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 34/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5359 - loss: 0.6906 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 35/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5354 - loss: 0.6907 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 36/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5351 - loss: 0.6907 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 37/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5367 - loss: 0.6905 - val_accuracy: 0.5332 - val_loss: 0.6911
Epoch 38/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5312 - loss: 0.6913 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 39/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5276 - loss: 0.6917 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 40/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5312 - loss: 0.6913 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 41/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.5363 - loss: 0.6906 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 42/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5356 - loss: 0.6908 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 43/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5304 - loss: 0.6914 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 44/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5285 - loss: 0.6916 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 45/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5324 - loss: 0.6911 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 46/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5330 - loss: 0.6910 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 47/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5347 - loss: 0.6908 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 48/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5322 - loss: 0.6911 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 49/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5345 - loss: 0.6908 - val_accuracy: 0.5332 - val_loss: 0.6912
Epoch 50/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.5345 - loss: 0.6910 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 51/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5290 - loss: 0.6915 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 52/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5344 - loss: 0.6908 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 53/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5257 - loss: 0.6919 - val_accuracy: 0.5332 - val_loss: 0.6912
Epoch 54/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5340 - loss: 0.6908 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 55/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5346 - loss: 0.6908 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 56/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5327 - loss: 0.6910 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 57/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5348 - loss: 0.6908 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 58/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5311 - loss: 0.6913 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 59/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5357 - loss: 0.6906 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 60/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5277 - loss: 0.6917 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 61/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5341 - loss: 0.6909 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 62/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5321 - loss: 0.6912 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 63/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5323 - loss: 0.6911 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 64/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5374 - loss: 0.6905 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 65/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5336 - loss: 0.6910 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 66/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5298 - loss: 0.6914 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 67/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5291 - loss: 0.6915 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 68/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.5367 - loss: 0.6905 - val_accuracy: 0.5332 - val_loss: 0.6912
Epoch 69/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5340 - loss: 0.6911 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 70/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5301 - loss: 0.6914 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 71/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5367 - loss: 0.6905 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 72/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5263 - loss: 0.6918 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 73/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5302 - loss: 0.6913 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 74/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5313 - loss: 0.6912 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 75/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5320 - loss: 0.6912 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 76/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5307 - loss: 0.6913 - val_accuracy: 0.5332 - val_loss: 0.6911
Epoch 77/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.5334 - loss: 0.6910 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 78/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5338 - loss: 0.6910 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 79/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5369 - loss: 0.6906 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 80/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5314 - loss: 0.6912 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 81/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5348 - loss: 0.6908 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 82/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5375 - loss: 0.6905 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 83/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5275 - loss: 0.6917 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 84/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5292 - loss: 0.6916 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 85/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5315 - loss: 0.6912 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 86/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.5323 - loss: 0.6912 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 87/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5299 - loss: 0.6914 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 88/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5277 - loss: 0.6917 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 89/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5285 - loss: 0.6917 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 90/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5315 - loss: 0.6912 - val_accuracy: 0.5332 - val_loss: 0.6911
Epoch 91/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5288 - loss: 0.6917 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 92/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5316 - loss: 0.6911 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 93/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5333 - loss: 0.6910 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 94/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5317 - loss: 0.6912 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 95/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.5315 - loss: 0.6913 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 96/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5254 - loss: 0.6921 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 97/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5304 - loss: 0.6914 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 98/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5282 - loss: 0.6917 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 99/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5298 - loss: 0.6915 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 100/100
402/402 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5352 - loss: 0.6908 - val_accuracy: 0.5332 - val_loss: 0.6910

In [18]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - 3ms/step - accuracy: 0.5331 - loss: 0.7632
Loss: 0.7631507515907288, Accuracy: 0.5330612063407898

In [19]:
# Export our model to HDF5 file
nn.save('AlphabetSoupCharity.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

#### Overview:
The goal of this analysis is to create a model that can predict whether organizations funded by Alphabet Soup will be successful, based on various features like application type, income, and funding request.

#### Results:
- **Target Variable**: The target is `IS_SUCCESSFUL`, which tells us if the organization was successful with the funding.
- **Features**: We used columns like application type, affiliation, and funding amount, while excluding `IS_SUCCESSFUL`, `EIN`, and `NAME`.
- **Removed Variables**: `EIN` and `NAME` were removed since they are just identifiers and don’t help with predictions.

#### Model:
- **Neurons and Layers**: 
  - The input layer has 128 neurons with **ReLU** activation to process the features.
  - A second hidden layer with 64 neurons and **ReLU** activation to learn more complex patterns.
  - The output layer has 1 neuron with **Sigmoid** activation to predict the success rate (binary outcome).
- **Optimizer and Loss**: The model was compiled using the **Adam** optimizer and **binary cross-entropy** as the loss function, with accuracy as the evaluation metric.

#### Performance:
- The initial model achieved an accuracy of **72%**, which is below the target of **75%**.
- To improve performance, we added **dropout layers** to avoid overfitting, increased the number of neurons, and added a third hidden layer.

#### Recommendation:
- **Random Forest** could be a good alternative for this task, as it handles categorical data well and is less prone to overfitting compared to deep learning models.